In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('eleague_raw.csv')

In [3]:
df = df.dropna(axis=1)

In [4]:
df

,season,match,game1,game2,game3
0,23,Chappa Flays vs Team Mellif (2-1),1. Team Mellif pick Inferno; (16-8),2. Chappa Flays pick Nuke; (16-19),3. Vertigo (16-12)
1,23,Lepido eSports vs Dixxi Riders (0-2),1. Dixxi Riders pick Inferno;(8-16),2. Lepido eSports pick Dust2;(7-16),3. Mirage
2,23,Bowl eSports vs Monarz Five (2-1),1. Monarz Five pick Overpass;(17-19),2. Bowl eSports pick Vertigo;(16-8),3. Nuke ;(19-17)
3,23,Desafinado Academy vs Bandi Soilders (2-1),1. Bandi Soilders pick Dust2; (7-16),2. Desafinado Academy pick Ancient; (16-10),3. Mirage (16-9)
4,23,Team Crimbe vs Rainbow Riders (1-2),1. Rainbow Riders pick Overpass; (11-16),2. Team Crimbe pick Dust2; (19-16),3. Inferno (11-16)
...,...,...,...,...,...
342,22,Rewice Gaming vs Duck eSports (2-0),1. Duck eSports pick Inferno; (16-10),2. Rewice Gaming pick Mirage; (16-13),3. Vertigo
343,22,Cherizy eSports vs Team Solitude (0-2),1. Team Solitude pick Nuke;(12-16),2. Cherizy eSports pick Inferno;(9-16),3. Vertigo
344,22,Dixxi Riders vs Kunzite Gaming (2-0),1. Kunzite Gaming pick Dust2; (16-11),2. Dixxi Riders pick Overpass; (16-6),3. Ancient
345,22,Squeezi Boars vs Team Sudio (0-2),1. Team Sudio pick Dust2;(8-16),2. Squeezi Boars pick Mirage;(7-16),3. Ancient
346,22,Team Solitude vs Marriz Gaming(2-0),1. Marriz Gaming pick Ancient;(16-12),2. Team Solitude pick Mirage;(19-17),3. Dust2

In [5]:
### clean match column
df[['team1', 'temp']] = df['match'].str.split(' vs ', 1, expand=True)
df[['team2', 'score']] = df['temp'].str.split('(', 1, expand=True)
df[['t1_score', 't2_score']] = df['score'].str.split('-', 1, expand=True)
df['t2_score'] = df['t2_score'].str.replace(')','')
df = df.drop(columns=['match', 'temp', 'score'])

C:\Users\assau\AppData\Local\Temp\ipykernel_5652\1541088586.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['t2_score'] = df['t2_score'].str.replace(')','')

In [6]:
### clean game1 column
df[['map1_pick', 'temp']] = df['game1'].str.split(' pick ', 1, expand=True)
df[['map1', 'map1_score']] = df['temp'].str.split(';', 1, expand=True)
df[['map1_t1', 'map1_t2']] = df['map1_score'].str.split('-', 1, expand=True)
df['map1_t1'] = df['map1_t1'].str.replace('(','')
df['map1_t2'] = df['map1_t2'].str.replace(')','')
df['map1_pick'] = df['map1_pick'].str[3:]
df = df.drop(columns=['game1', 'temp', 'map1_score'])

C:\Users\assau\AppData\Local\Temp\ipykernel_5652\3690049230.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['map1_t1'] = df['map1_t1'].str.replace('(','')
C:\Users\assau\AppData\Local\Temp\ipykernel_5652\3690049230.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['map1_t2'] = df['map1_t2'].str.replace(')','')

In [7]:
### clean game2 column
df[['map2_pick', 'temp']] = df['game2'].str.split(' pick ', 1, expand=True)
df[['map2', 'map2_score']] = df['temp'].str.split(';', 1, expand=True)
df[['map2_t1', 'map2_t2']] = df['map2_score'].str.split('-', 1, expand=True)
df['map2_t1'] = df['map2_t1'].str.replace('(','')
df['map2_t2'] = df['map2_t2'].str.replace(')','')
df['map2_pick'] = df['map2_pick'].str[3:]
df = df.drop(columns=['game2', 'temp', 'map2_score'])

C:\Users\assau\AppData\Local\Temp\ipykernel_5652\2893478554.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['map2_t1'] = df['map2_t1'].str.replace('(','')
C:\Users\assau\AppData\Local\Temp\ipykernel_5652\2893478554.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['map2_t2'] = df['map2_t2'].str.replace(')','')

In [8]:
### clean game3 column
df[['map3', 'map3_score']] = df['game3'].str.split('(', 1, expand=True)
df['map3'] = df['map3'].str[3:]
df['map3'] = df['map3'].str.strip(' ;')
df['map3_score'] = df['map3_score'].str.replace(')','')
df[['map3_t1', 'map3_t2']] = df['map3_score'].str.split('-', 1, expand=True)
df = df.drop(columns=['game3', 'map3_score'])

C:\Users\assau\AppData\Local\Temp\ipykernel_5652\266817647.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['map3_score'] = df['map3_score'].str.replace(')','')

In [9]:
df

,season,team1,team2,t1_score,t2_score,map1_pick,map1,map1_t1,map1_t2,map2_pick,map2,map2_t1,map2_t2,map3,map3_t1,map3_t2
0,23,Chappa Flays,Team Mellif,2,1,Team Mellif,Inferno,16,8,Chappa Flays,Nuke,16,19,Vertigo,16,12
1,23,Lepido eSports,Dixxi Riders,0,2,Dixxi Riders,Inferno,8,16,Lepido eSports,Dust2,7,16,Mirage,None,None
2,23,Bowl eSports,Monarz Five,2,1,Monarz Five,Overpass,17,19,Bowl eSports,Vertigo,16,8,Nuke,19,17
3,23,Desafinado Academy,Bandi Soilders,2,1,Bandi Soilders,Dust2,7,16,Desafinado Academy,Ancient,16,10,Mirage,16,9
4,23,Team Crimbe,Rainbow Riders,1,2,Rainbow Riders,Overpass,11,16,Team Crimbe,Dust2,19,16,Inferno,11,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,22,Rewice Gaming,Duck eSports,2,0,Duck eSports,Inferno,16,10,Rewice Gaming,Mirage,16,13,Vertigo,None,None
343,22,Cherizy eSports,Team Solitude,0,2,Team Solitude,Nuke,12,16,Cherizy eSports,Inferno,9,16,Vertigo,None,None
344,22,Dixxi Riders,Kunzite Gaming,2,0,Kunzite Gaming,Dust2,16,11,Dixxi Riders,Overpass,16,6,Ancient,None,None
345,22,Squeezi Boars,Team Sudio,0,2,Team Sudio,Dust2,8,16,Squeezi Boars,Mirage,7,16,Ancient,None,None
346,22,Team Solitude,Marriz Gaming,2,0,Marriz Gaming,Ancient,16,12,Team Solitude,Mirage,19,17,Dust2,None,None

In [10]:
### functions

# retrieve games involving the specified teams
def results(team1_name, team2_name):
    df2 = df[(df.team1 == team1_name) | (df.team2 == team1_name)]
    df3 = df[(df.team1 == team2_name) | (df.team2 == team2_name)]
    df4 = pd.concat([df2,df3])
    return df4

### Team List
- Bandi Soilders
- Bowl eSports
- Chappa Flays
- Cherizy eSports
- Desafinado Academy
- Dixxi Riders
- Hako Gaming
- Kunzite Gaming
- Leemaz Clan
- Lepido eSports
- Marriz Gaming
- Midnight Academy
- Monarz Five
- qK
- Rainbow Riders
- Rewice Gaming
- Rozippe Gaming
- Squeezi Boars
- Team Crimbe
- Team Kayzze
- Team Mellif
- Team Orbis
- Team Priestly
- Team Shipin
- Team Solitude
- Team Sudio
- Tweezar Crusaders
- WPG
- Wups Gaming
- Yowi Rising

In [11]:
df

,season,team1,team2,t1_score,t2_score,map1_pick,map1,map1_t1,map1_t2,map2_pick,map2,map2_t1,map2_t2,map3,map3_t1,map3_t2
0,23,Chappa Flays,Team Mellif,2,1,Team Mellif,Inferno,16,8,Chappa Flays,Nuke,16,19,Vertigo,16,12
1,23,Lepido eSports,Dixxi Riders,0,2,Dixxi Riders,Inferno,8,16,Lepido eSports,Dust2,7,16,Mirage,None,None
2,23,Bowl eSports,Monarz Five,2,1,Monarz Five,Overpass,17,19,Bowl eSports,Vertigo,16,8,Nuke,19,17
3,23,Desafinado Academy,Bandi Soilders,2,1,Bandi Soilders,Dust2,7,16,Desafinado Academy,Ancient,16,10,Mirage,16,9
4,23,Team Crimbe,Rainbow Riders,1,2,Rainbow Riders,Overpass,11,16,Team Crimbe,Dust2,19,16,Inferno,11,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,22,Rewice Gaming,Duck eSports,2,0,Duck eSports,Inferno,16,10,Rewice Gaming,Mirage,16,13,Vertigo,None,None
343,22,Cherizy eSports,Team Solitude,0,2,Team Solitude,Nuke,12,16,Cherizy eSports,Inferno,9,16,Vertigo,None,None
344,22,Dixxi Riders,Kunzite Gaming,2,0,Kunzite Gaming,Dust2,16,11,Dixxi Riders,Overpass,16,6,Ancient,None,None
345,22,Squeezi Boars,Team Sudio,0,2,Team Sudio,Dust2,8,16,Squeezi Boars,Mirage,7,16,Ancient,None,None
346,22,Team Solitude,Marriz Gaming,2,0,Marriz Gaming,Ancient,16,12,Team Solitude,Mirage,19,17,Dust2,None,None

In [12]:
t1 = 'Team Orbis'
t2 = 'Team Priestly'
temp = results(t1, t2)
temp.to_csv('temp.csv')